add_subdirectory(GPU)

add_triton_library(IREECodegenCommon
    CleanupBufferAllocViewPass.cpp
    ConfigTrackingCanonicalizer.cpp
    IREEComprehensiveBufferizePass.cpp
    Passes.cpp
    ReplaceSlowMinMaxOps.cpp
    TileDispatchUsingForall.cpp
    TileDispatchUsingInterface.cpp
    PassUtils.cpp
    OptimizeTensorInsertExtractSlices.cpp
    OptimizeVectorTransferPass.cpp
    FoldTensorSubsetIntoVectorTransferOps.cpp
    MemrefCopyToLinalg.cpp
    IREELoopInvariantCodeMotion.cpp
    ReconcileTranslationInfo.cpp
    VerifyWorkgroupDistribution.cpp
    HoistStaticallyBoundAllocations.cpp
    PadDynamicAlloc.cpp
    FoldTensorExtractOpPass.cpp
    ExpandGPUOps.cpp
    DecomposeAffineOpsPass.cpp
    ExtractAddressComputation.cpp
    ConvertBf16ArithToF32.cpp
    ConvertBf16ToUInt16Buffers.cpp
    PolynomialApproximationPass.cpp
    EmulateNarrowType.cpp
    IREEExpandStridedMetadata.cpp
    TransferReadSubviewFusion.cpp
    TransferReadToVectorTransferRead.cpp
    NormalizeLoopBounds.cpp
    TileLargeTensors.cpp
    UnrollAnnotatedLoops.cpp
    DecomposeConvolutionToLowerDimOps.cpp
    VectorizeMemrefCopy.cpp
    GenericVectorization.cpp
    TileSizeSelection.cpp
    
DEPENDS
    CommonCodegenPassIncGen
    FoldTensorExtractOpIncGen
LINK_LIBS PUBLIC
    LLVMSupport
    MLIRAffineAnalysis
    MLIRAffineDialect
    MLIRAffineTransforms
    MLIRAffineUtils
    MLIRAnalysis
    MLIRArithDialect
    MLIRArithTransforms
    MLIRArithUtils
    MLIRBufferizationDialect
    MLIRBufferizationTransforms
    MLIRBytecodeWriter
    MLIRDestinationStyleOpInterface
    MLIRFuncDialect
    MLIRFuncTransforms
    MLIRFunctionInterfaces
    MLIRGPUDialect
    MLIRIR
    MLIRLLVMCommonConversion
    MLIRLLVMDialect
    MLIRLinalgDialect
    MLIRLinalgTransforms
    MLIRLinalgUtils
    MLIRLoopLikeInterface
    MLIRMathDialect
    MLIRMathTransforms
    MLIRMemRefDialect
    MLIRMemRefTransforms
    MLIRMemRefUtils
    MLIRParser
    MLIRPass
    MLIRSCFDialect
    MLIRSCFToControlFlow
    MLIRSCFTransforms
    MLIRSCFUtils
    MLIRSideEffectInterfaces
    MLIRSubsetOpInterface
    MLIRSupport
    MLIRTensorDialect
    MLIRTensorTransforms
    MLIRTensorUtils
    MLIRTilingInterface
    MLIRTransformDialect
    MLIRTransformUtils
    MLIRTransforms
    MLIRValueBoundsOpInterface
    MLIRVectorDialect
    MLIRVectorTransforms
    MLIRViewLikeInterface
    IREECodegenTransforms
    IREECodegenDialect
    IREECodegenDialectUtils
    IREEGPUDialect
    IREEVectorExtDialect
    IREECodegenBufferizationInterfaces
    IREECodegenPartitionableLoopsInterface
    IREECodegenUKernelOpInterface
    IREEEncodingDialect
    IREECodegenUtils
)