add_subdirectory(Utils)

add_triton_library(IREECodegenLLVMGPU
 KernelConfig.cpp
 LLVMGPULowerExecutableTarget.cpp
 LLVMGPUSelectLoweringStrategy.cpp
 MaterializeTarget.cpp
 Passes.cpp
 Verifiers.cpp
 LLVMGPUCodegen.cpp
 LLVMGPUTileAndDistribute.cpp
 LLVMGPUTensorCoreVectorization.cpp
 LLVMGPUPackSharedMemoryAlloc.cpp
 LLVMGPUVectorToGPU.cpp
 LLVMGPUVectorLowering.cpp
 ExtractAddressComputationGPUPass.cpp
 
  DEPENDS
    LLVMGPUCodegenPassIncGen

  LINK_LIBS PUBLIC
  LLVMSupport
  MLIRAMDGPUDialect
  MLIRAMDGPUToROCDL
  MLIRAMDGPUTransforms
  MLIRAMDGPUUtils
  MLIRAffineDialect
  MLIRAffineToStandard
  MLIRAffineTransforms
  MLIRAnalysis
  MLIRArithDialect
  MLIRArithToAMDGPU
  MLIRArithToLLVM
  MLIRArithTransforms
  MLIRBufferizationDialect
  MLIRBufferizationTransforms
  MLIRComplexToLLVM
  MLIRComplexToStandard
  MLIRControlFlowToLLVM
  MLIRFuncDialect
  MLIRFuncToLLVM
  MLIRFuncTransforms
  MLIRFunctionInterfaces
  MLIRGPUDialect
  MLIRGPUToNVVMTransforms
  MLIRGPUToROCDLTransforms
  MLIRGPUTransformOps
  MLIRGPUTransforms
  MLIRIR
  MLIRLLVMCommonConversion
  MLIRLLVMDialect
  MLIRLinalgDialect
  MLIRLinalgTransforms
  MLIRMathDialect
  MLIRMathToLLVM
  MLIRMemRefDialect
  MLIRMemRefToLLVM
  MLIRMemRefTransforms
  MLIRNVGPUDialect
  MLIRNVGPUToNVVM
  MLIRNVGPUTransforms
  MLIRNVGPUUtils
  MLIRNVVMDialect
  MLIRNVVMToLLVM
  MLIRPDLDialect
  MLIRPDLInterpDialect
  MLIRPass
  MLIRSCFDialect
  MLIRSCFToControlFlow
  MLIRSCFTransforms
  MLIRSideEffectInterfaces
  MLIRSupport
  MLIRTensorDialect
  MLIRTransformDialect
  MLIRTransformUtils
  MLIRTransforms
  MLIRValueBoundsOpInterface
  MLIRVectorDialect
  MLIRVectorToGPU
  MLIRVectorToLLVM
  MLIRVectorToSCF
  MLIRVectorTransforms

  TTSUtils

  IREEGPUHeuristics
  IREECodegenDialect
  IREEGPUDialect
  IREEGPUConfigUtils
  IREEGPUDialectTransforms
  IREEVectorExtDialect
  IREEVectorExtTransforms
  IREECodegenPartitionableLoopsInterface
  IREECodegenUKernelOpInterface
  IREECodegenUtils
  IREECodegenTransforms
  IREECodegenVectorOpUtils
  IREECodegenLLVMGPUUtils
  IREECodegenCommon
  IREECodegenCommonGPUPasses
)
# iree::compiler::Codegen::Common::TransformDialectInterpreterPass
# iree::compiler::Codegen::Common::VectorLayoutAnalysis
