add_subdirectory(Utils)
add_subdirectory(TritonNVIDIAGPUToLLVM)

add_triton_library(IREECodegenLLVMGPU
 KernelConfig.cpp
 LLVMGPULowerExecutableTarget.cpp
 LLVMGPUSelectLoweringStrategy.cpp
 MaterializeTarget.cpp
 Passes.cpp
 Verifiers.cpp
 LLVMGPUCodegen.cpp
 LLVMGPUTileAndDistribute.cpp
 LLVMGPUTensorCoreVectorization.cpp
 LLVMGPUPackSharedMemoryAlloc.cpp
 LLVMGPUVectorToGPU.cpp
 LLVMGPUVectorLowering.cpp
 LLVMGPUVectorTransferReadOptimize.cpp
 ExtractAddressComputationGPUPass.cpp
 LLVMGPUCastAddressSpaceFunction.cpp
 ConvertToNVVM.cpp
 ConvertToLLVM.cpp
 SerializeExecutables.cpp
 LLVMGPUPrefetching.cpp
 SPMDOp.cpp
 PtrTransform.cpp
 TensorTransferWriteFusion.cpp

  DEPENDS
    LLVMGPUCodegenPassIncGen

  LINK_LIBS PUBLIC
  LLVMSupport
  LLVMAnalysis
  LLVMBitReader
  LLVMBitWriter
  LLVMCore
  LLVMLinker
  LLVMMC
  LLVMNVPTXCodeGen
  LLVMNVPTXDesc
  LLVMNVPTXInfo
  LLVMPasses
  LLVMSupport
  LLVMTarget
  LLVMipo
  LLVMNVPTXInfo

  MLIRAMDGPUDialect
  MLIRAMDGPUToROCDL
  MLIRAMDGPUTransforms
  MLIRAMDGPUUtils
  MLIRAffineDialect
  MLIRAffineToStandard
  MLIRAffineTransforms
  MLIRAnalysis
  MLIRArithDialect
  MLIRArithToAMDGPU
  MLIRArithToLLVM
  MLIRArithTransforms
  MLIRBufferizationDialect
  MLIRBufferizationTransforms
  MLIRComplexToLLVM
  MLIRComplexToStandard
  MLIRControlFlowToLLVM
  MLIRFuncDialect
  MLIRFuncToLLVM
  MLIRFuncTransforms
  MLIRFunctionInterfaces
  MLIRGPUDialect
  MLIRGPUToNVVMTransforms
  MLIRGPUToROCDLTransforms
  MLIRGPUTransformOps
  MLIRGPUTransforms
  MLIRIR
  MLIRLLVMCommonConversion
  MLIRLLVMDialect
  MLIRLinalgDialect
  MLIRLinalgTransforms
  MLIRMathDialect
  MLIRMathToLLVM
  MLIRMemRefDialect
  MLIRMemRefToLLVM
  MLIRMemRefTransforms
  MLIRNVGPUDialect
  MLIRNVGPUToNVVM
  MLIRNVGPUTransforms
  MLIRNVGPUUtils
  MLIRNVVMDialect
  MLIRNVVMToLLVM
  MLIRPDLDialect
  MLIRPDLInterpDialect
  MLIRPass
  MLIRSCFDialect
  MLIRSCFToControlFlow
  MLIRSCFTransforms
  MLIRSideEffectInterfaces
  MLIRSupport
  MLIRTensorDialect
  MLIRTransformDialect
  MLIRTransformUtils
  MLIRTransforms
  MLIRValueBoundsOpInterface
  MLIRVectorDialect
  MLIRVectorToGPU
  MLIRVectorToLLVM
  MLIRVectorToSCF
  MLIRVectorTransforms
  MLIRBuiltinToLLVMIRTranslation
  MLIRLLVMToLLVMIRTranslation
  MLIRNVVMToLLVMIRTranslation
  MLIRTargetLLVMIRExport

  TTSUtils
  TritonStructuredIR
  TritonIR
  TritonToLinalgExperimental
  

  IREEGPUHeuristics
  IREECodegenDialect
  IREEGPUDialect
  IREEGPUConfigUtils
  IREEGPUDialectTransforms
  IREEVectorExtDialect
  IREEVectorExtTransforms
  IREECodegenPartitionableLoopsInterface
  IREECodegenUKernelOpInterface
  IREECodegenUtils
  IREECodegenTransforms
  IREECodegenVectorOpUtils
  IREECodegenLLVMGPUUtils
  IREECodegenCommon
  IREECodegenCommonGPUPasses
  TTSNVIDIAGPUToLLVM
)
# iree::compiler::Codegen::Common::TransformDialectInterpreterPass
# iree::compiler::Codegen::Common::VectorLayoutAnalysis
